In [1]:
import pandas as pd
from sqlalchemy import create_engine

#SQLAlchemy Connection
engine = create_engine('mysql+mysqlconnector://3RpS6E8vJViaNcJ.root:5mAbJNUlK8UUO6DW@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/nifty50_db')

In [ ]:
stock_query= f"""SELECT * FROM nifty50_tb;"""
df=pd.read_sql(stock_query, engine)
print(df)

       stock_no      Ticker    close        date     high      low  month  \
0             1        SBIN   566.40  2023-11-01   569.65   563.85     11
1             2  BAJFINANCE  7471.90  2023-11-01  7549.00  7457.65     11
2             3       TITAN  3173.40  2023-11-01  3212.90  3168.35     11
3             4         ITC   428.10  2023-11-01   431.10   425.50     11
4             5         TCS  3330.65  2023-11-01  3371.60  3311.00     11
...         ...         ...      ...         ...      ...      ...    ...
13195     13196    HINDALCO   652.10  2024-11-22   657.30   647.40     11
13196     13197  HEROMOTOCO  4794.10  2024-11-22  4808.40  4742.00     11
13197     13198    AXISBANK  1142.40  2024-11-22  1147.90  1127.55     11
13198     13199    HDFCBANK  1745.60  2024-11-22  1754.30  1729.55     11
13199     13200  BAJAJ-AUTO  9481.65  2024-11-22  9602.90  9444.10     11

          open    volume  year
0       566.25  13575575  2023
1      7520.00    462778  2023
2      3193.85    756820  2023
3       430.00   7990245  2023
4      3355.00   1563475  2023
...        ...       ...   ...
13195   652.95   3586402  2024
13196  4778.40    394712  2024
13197  1136.65  16687505  2024
13198  1743.55  12386806  2024
13199  9545.00    619823  2024

[13200 rows x 10 columns]

In [4]:
df

,stock_no,Ticker,close,date,high,low,month,open,volume,year
0,1,SBIN,566.40,2023-11-01,569.65,563.85,11,566.25,13575575,2023
1,2,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,11,7520.00,462778,2023
2,3,TITAN,3173.40,2023-11-01,3212.90,3168.35,11,3193.85,756820,2023
3,4,ITC,428.10,2023-11-01,431.10,425.50,11,430.00,7990245,2023
4,5,TCS,3330.65,2023-11-01,3371.60,3311.00,11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...,...
13195,13196,HINDALCO,652.10,2024-11-22,657.30,647.40,11,652.95,3586402,2024
13196,13197,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,11,4778.40,394712,2024
13197,13198,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,11,1136.65,16687505,2024
13198,13199,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,11,1743.55,12386806,2024
13199,13200,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,11,9545.00,619823,2024

In [6]:
df_b=df.copy()

In [17]:
#Top 10 Green Stocks: Sort the stocks based on their yearly return and select the top 10.

df = df.sort_values(['Ticker', 'date'])
df

,stock_no,Ticker,close,date,high,low,month,open,volume,year
24,25,ADANIENT,2217.30,2023-11-01,2312.25,2207.00,11,2299.00,1666579,2023
74,75,ADANIENT,2215.30,2023-11-02,2297.95,2204.20,11,2247.00,2340997,2023
124,125,ADANIENT,2229.85,2023-11-03,2279.00,2215.00,11,2215.30,1853300,2023
174,175,ADANIENT,2246.00,2023-11-06,2260.00,2233.00,11,2253.95,770061,2023
224,225,ADANIENT,2233.35,2023-11-07,2260.00,2226.65,11,2257.00,641554,2023
...,...,...,...,...,...,...,...,...,...,...
12966,12967,WIPRO,566.70,2024-11-14,574.55,564.20,11,568.95,4891760,2024
13016,13017,WIPRO,552.85,2024-11-18,566.70,540.30,11,566.70,7644882,2024
13066,13067,WIPRO,562.00,2024-11-19,569.80,554.70,11,556.00,6459889,2024
13116,13117,WIPRO,557.15,2024-11-21,567.60,555.30,11,562.00,5836304,2024
13166,13167,WIPRO,571.65,2024-11-22,573.60,557.90,11,561.95,7366616,2024

In [10]:
df

,stock_no,Ticker,close,date,high,low,month,open,volume,year
24,25,ADANIENT,2217.30,2023-11-01,2312.25,2207.00,11,2299.00,1666579,2023
74,75,ADANIENT,2215.30,2023-11-02,2297.95,2204.20,11,2247.00,2340997,2023
124,125,ADANIENT,2229.85,2023-11-03,2279.00,2215.00,11,2215.30,1853300,2023
174,175,ADANIENT,2246.00,2023-11-06,2260.00,2233.00,11,2253.95,770061,2023
224,225,ADANIENT,2233.35,2023-11-07,2260.00,2226.65,11,2257.00,641554,2023
...,...,...,...,...,...,...,...,...,...,...
12966,12967,WIPRO,566.70,2024-11-14,574.55,564.20,11,568.95,4891760,2024
13016,13017,WIPRO,552.85,2024-11-18,566.70,540.30,11,566.70,7644882,2024
13066,13067,WIPRO,562.00,2024-11-19,569.80,554.70,11,556.00,6459889,2024
13116,13117,WIPRO,557.15,2024-11-21,567.60,555.30,11,562.00,5836304,2024
13166,13167,WIPRO,571.65,2024-11-22,573.60,557.90,11,561.95,7366616,2024

In [11]:
start = df.groupby(['Ticker', 'year']).first().reset_index()[['Ticker', 'year', 'close']]

In [12]:
start

        Ticker  year     close
0     ADANIENT  2023   2217.30
1     ADANIENT  2024   2917.20
2   ADANIPORTS  2023    769.10
3   ADANIPORTS  2024   1047.85
4   APOLLOHOSP  2023   4796.55
..         ...   ...       ...
95       TRENT  2024   3002.10
96  ULTRACEMCO  2023   8381.45
97  ULTRACEMCO  2024  10464.00
98       WIPRO  2023    380.95
99       WIPRO  2024    477.15

[100 rows x 3 columns]

In [18]:
end = df.groupby(['Ticker', 'year']).last().reset_index()[['Ticker', 'year', 'close']]

In [19]:
end

        Ticker  year     close
0     ADANIENT  2023   2848.95
1     ADANIENT  2024   2228.00
2   ADANIPORTS  2023   1024.35
3   ADANIPORTS  2024   1136.75
4   APOLLOHOSP  2023   5704.10
..         ...   ...       ...
95       TRENT  2024   6652.80
96  ULTRACEMCO  2023  10503.00
97  ULTRACEMCO  2024  11375.30
98       WIPRO  2023    471.30
99       WIPRO  2024    571.65

[100 rows x 3 columns]

In [ ]:
start = df.groupby(['Ticker', 'year']).first().reset_index()[['Ticker', 'year', 'close']]
end = df.groupby(['Ticker', 'year']).last().reset_index()[['Ticker', 'year', 'close']]
# Merge start and end to compute return
returns_df = pd.merge(start, end, on=['Ticker', 'year'], suffixes=('_start', '_end'))
# Calculate % return
returns_df['yearly_return'] = ((returns_df['close_end'] - returns_df['close_start']) / returns_df['close_start']) * 100
latest_year = returns_df['year'].max() #Top 10 Green Stocks (for the most recent year)
top_10_green = returns_df[returns_df['year'] == latest_year].sort_values(by='yearly_return', ascending=False).head(10)
print("✅ Top 10 Green Stocks:")
print(top_10_green[['Ticker', 'year', 'yearly_return']])

✅ Top 10 Green Stocks:
        Ticker  year  yearly_return
95       TRENT  2024     121.604877
61         M&M  2024      76.888980
19  BHARTIARTL  2024      54.908445
17         BEL  2024      51.851852
81   SUNPHARMA  2024      42.455862
11  BAJAJ-AUTO  2024      41.493934
71   POWERGRID  2024      41.427072
79  SHRIRAMFIN  2024      39.104864
91       TECHM  2024      34.714567
35     HCLTECH  2024      27.946083

In [31]:
# Sort and group
df1 = df.sort_values(['Ticker', 'date'])
strt = df1.groupby(['Ticker','year']).first()['close']
end = df1.groupby(['Ticker','year']).last()['close']

# Calculate yearly return
returns = ((end - strt) / strt) * 100
ret_df = returns.reset_index().rename(columns={'close': 'yearly_return'})

# Top 10 Green Stocks
green_10 = ret_df.sort_values(by='yearly_return', ascending=False).head(10)
loss_10 = ret_df.sort_values(by='yearly_return', ascending=False).tail(10)
print("✅ Top 10 Green Stocks:")
print(green_10)
print("✅ Top 10 Loss Stocks:")
print(loss_10)

✅ Top 10 Green Stocks:
        Ticker  year  yearly_return
95       TRENT  2024     121.604877
61         M&M  2024      76.888980
19  BHARTIARTL  2024      54.908445
17         BEL  2024      51.851852
81   SUNPHARMA  2024      42.455862
11  BAJAJ-AUTO  2024      41.493934
71   POWERGRID  2024      41.427072
16         BEL  2023      39.123867
79  SHRIRAMFIN  2024      39.104864
94       TRENT  2023      39.009851
✅ Top 10 Loss Stocks:
        Ticker  year  yearly_return
57   KOTAKBANK  2024      -7.736427
45  HINDUNILVR  2024      -7.891515
15  BAJFINANCE  2024      -8.427124
23   BRITANNIA  2024      -8.862175
93       TITAN  2024     -10.019988
83  TATACONSUM  2024     -11.401897
65   NESTLEIND  2024     -17.899052
1     ADANIENT  2024     -23.625394
7   ASIANPAINT  2024     -27.204735
49  INDUSINDBK  2024     -37.567627

In [ ]:
# Market Summary:

In [ ]:
# Calculate the overall number of green vs. red stocks.
green_stock = ret_df[ret_df['yearly_return'] > 0].shape[0]
red_stock = ret_df[ret_df['yearly_return'] < 0].shape[0]

# Print results
print(f"✅ Green Stocks (positive return): {green_stock}")
print(f"❌ Red Stocks (negative return): {red_stock}")

✅ Green Stocks (positive return): 87
❌ Red Stocks (negative return): 13

In [38]:
# Calculate the average price across all stocks.
avg_price_stock = df.groupby('Ticker')['close'].mean().reset_index().rename(columns={'close': 'avg_price'})
print(avg_price_stock)

        Ticker     avg_price
0     ADANIENT   2995.450000
1   ADANIPORTS   1295.323864
2   APOLLOHOSP   6283.286553
3   ASIANPAINT   3013.064773
4     AXISBANK   1136.336742
5   BAJAJ-AUTO   8844.334659
6   BAJAJFINSV   1656.798864
7   BAJFINANCE   7030.633712
8          BEL    240.964962
9   BHARTIARTL   1320.360985
10        BPCL    294.050909
11   BRITANNIA   5304.688636
12       CIPLA   1449.498106
13   COALINDIA    445.472348
14     DRREDDY   1242.534394
15   EICHERMOT   4388.398106
16      GRASIM   2388.160947
17     HCLTECH   1563.175000
18    HDFCBANK   1582.813258
19    HDFCLIFE    643.680114
20  HEROMOTOCO   4807.165720
21    HINDALCO    619.348864
22  HINDUNILVR   2535.155871
23   ICICIBANK   1123.208902
24  INDUSINDBK   1443.094697
25        INFY   1644.927652
26         ITC    455.612121
27    JSWSTEEL    882.729167
28   KOTAKBANK   1775.430682
29          LT   3517.828598
30         M&M   2304.953030
31      MARUTI  11717.419129
32   NESTLEIND   2500.963750
33        NTPC    354.492614
34        ONGC    265.905871
35   POWERGRID    293.642614
36    RELIANCE   1405.796742
37     SBILIFE   1544.960795
38        SBIN    755.016477
39  SHRIRAMFIN   2624.758333
40   SUNPHARMA   1558.190909
41  TATACONSUM   1093.173788
42  TATAMOTORS    915.775568
43   TATASTEEL    151.397576
44         TCS   3986.492424
45       TECHM   1398.034470
46       TITAN   3510.466288
47       TRENT   4868.125000
48  ULTRACEMCO  10415.427652
49       WIPRO    490.964394

In [ ]:
# Calculate the average Volume across all stocks.
pd.set_option('display.float_format', '{:.2f}'.format)
avg_vol_stock = df.groupby('Ticker')['volume'].mean().reset_index().rename(columns={'volume': 'avg_volume_stocks'})
print(avg_vol_stock)

        Ticker  avg_volume_stocks
0     ADANIENT         2422093.05
1   ADANIPORTS         4937183.07
2   APOLLOHOSP          435387.43
3   ASIANPAINT         1237036.05
4     AXISBANK         9701016.02
5   BAJAJ-AUTO          496874.51
6   BAJAJFINSV         1563918.74
7   BAJFINANCE         1196773.53
8          BEL        29801017.72
9   BHARTIARTL         6302605.05
10        BPCL        16843563.62
11   BRITANNIA          346226.10
12       CIPLA         1825797.08
13   COALINDIA        12124048.21
14     DRREDDY         2073022.44
15   EICHERMOT          654221.91
16      GRASIM          809051.62
17     HCLTECH         3013897.58
18    HDFCBANK        20374220.12
19    HDFCLIFE         4481345.65
20  HEROMOTOCO          748548.58
21    HINDALCO         7121934.56
22  HINDUNILVR         1899606.91
23   ICICIBANK        15284190.96
24  INDUSINDBK         4002770.08
25        INFY         6829218.00
26         ITC        14501044.78
27    JSWSTEEL         2271812.04
28   KOTAKBANK         5473338.97
29          LT         2451124.04
30         M&M         3165202.90
31      MARUTI          569415.16
32   NESTLEIND          931878.69
33        NTPC        16945373.05
34        ONGC        19399809.31
35   POWERGRID        17869835.84
36    RELIANCE        12745474.88
37     SBILIFE         1373337.87
38        SBIN        17748261.95
39  SHRIRAMFIN         1425213.74
40   SUNPHARMA         2235526.72
41  TATACONSUM         1748222.86
42  TATAMOTORS        12190135.41
43   TATASTEEL        45315269.75
44         TCS         2347539.58
45       TECHM         2173493.97
46       TITAN         1169980.85
47       TRENT          909699.98
48  ULTRACEMCO          352302.26
49       WIPRO         8047886.04

In [67]:
df

,stock_no,Ticker,close,date,high,low,month,open,volume,year
0,1,SBIN,566.40,2023-11-01,569.65,563.85,11,566.25,13575575,2023
1,2,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,11,7520.00,462778,2023
2,3,TITAN,3173.40,2023-11-01,3212.90,3168.35,11,3193.85,756820,2023
3,4,ITC,428.10,2023-11-01,431.10,425.50,11,430.00,7990245,2023
4,5,TCS,3330.65,2023-11-01,3371.60,3311.00,11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...,...
13195,13196,HINDALCO,652.10,2024-11-22,657.30,647.40,11,652.95,3586402,2024
13196,13197,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,11,4778.40,394712,2024
13197,13198,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,11,1136.65,16687505,2024
13198,13199,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,11,1743.55,12386806,2024
13199,13200,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,11,9545.00,619823,2024

In [71]:
engine = create_engine('mysql+mysqlconnector://3RpS6E8vJViaNcJ.root:5mAbJNUlK8UUO6DW@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/nifty50_db')

# Load your data
df = pd.read_sql("SELECT * FROM nifty50_tb", con=engine)

In [72]:
df

,stock_no,Ticker,close,date,high,low,month,open,volume,year
0,1,SBIN,566.40,2023-11-01,569.65,563.85,11,566.25,13575575,2023
1,2,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,11,7520.00,462778,2023
2,3,TITAN,3173.40,2023-11-01,3212.90,3168.35,11,3193.85,756820,2023
3,4,ITC,428.10,2023-11-01,431.10,425.50,11,430.00,7990245,2023
4,5,TCS,3330.65,2023-11-01,3371.60,3311.00,11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...,...
13195,13196,HINDALCO,652.10,2024-11-22,657.30,647.40,11,652.95,3586402,2024
13196,13197,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,11,4778.40,394712,2024
13197,13198,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,11,1136.65,16687505,2024
13198,13199,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,11,1743.55,12386806,2024
13199,13200,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,11,9545.00,619823,2024

In [79]:
del df_c

In [103]:
df=pd.read_csv("D:\Data_Driven_stock_project\Sector_data.csv")

In [104]:
df

                 Ticker           sector                          Symbol
0     ADANI ENTERPRISES    MISCELLANEOUS   ADANI ENTERPRISES: ADANIGREEN
1     ADANI PORTS & SEZ    MISCELLANEOUS   ADANI PORTS & SEZ: ADANIPORTS
2      APOLLO HOSPITALS    MISCELLANEOUS    APOLLO HOSPITALS: APOLLOHOSP
3          ASIAN PAINTS           PAINTS        ASIAN PAINTS: ASIANPAINT
4             AXIS BANK          BANKING             AXIS BANK: AXISBANK
5            BAJAJ AUTO      AUTOMOBILES          BAJAJ AUTO: BAJAJ-AUTO
6         BAJAJ FINANCE          FINANCE       BAJAJ FINANCE: BAJFINANCE
7         BAJAJ FINSERV          FINANCE       BAJAJ FINSERV: BAJAJFINSV
8    BHARAT ELECTRONICS          DEFENCE         BHARAT ELECTRONICS: BEL
9         BHARTI AIRTEL          TELECOM           BHARTI AIRTEL: AIRTEL
10                 BPCL           ENERGY                      BPCL: BPCL
11                CIPLA  PHARMACEUTICALS                    CIPLA: CIPLA
12           COAL INDIA           MINING           COAL INDIA: COALINDIA
13       DR. REDDYS LAB  PHARMACEUTICALS         DR. REDDYS LAB: DRREDDY
14        EICHER MOTORS      AUTOMOBILES        EICHER MOTORS: EICHERMOT
15               GRASIM         TEXTILES                  GRASIM: GRASIM
16     HCL TECHNOLOGIES         SOFTWARE       HCL TECHNOLOGIES: HCLTECH
17            HDFC BANK          BANKING             HDFC BANK: HDFCBANK
18  HDFC LIFE INSURANCE        INSURANCE   HDFC LIFE INSURANCE: HDFCLIFE
19        HERO MOTOCORP      AUTOMOBILES       HERO MOTOCORP: HEROMOTOCO
20             HINDALCO        ALUMINIUM              HINDALCO: HINDALCO
21   HINDUSTAN UNILEVER             FMCG  HINDUSTAN UNILEVER: HINDUNILVR
22           ICICI BANK          BANKING           ICICI BANK: ICICIBANK
23        INDUSIND BANK          BANKING       INDUSIND BANK: INDUSINDBK
24              INFOSYS         SOFTWARE                   INFOSYS: INFY
25                  IOC           ENERGY                        IOC: IOC
26                  ITC   FOOD & TOBACCO                        ITC: ITC
27            JSW STEEL            STEEL             JSW STEEL: JSWSTEEL
28  KOTAK MAHINDRA BANK          BANKING  KOTAK MAHINDRA BANK: KOTAKBANK
29                  L&T      ENGINEERING                         L&T: LT
30                  M&M      AUTOMOBILES                        M&M: M&M
31        MARUTI SUZUKI      AUTOMOBILES           MARUTI SUZUKI: MARUTI
32               NESTLE   FOOD & TOBACCO               NESTLE: NESTLEIND
33                 NTPC            POWER                      NTPC: NTPC
34                 ONGC           ENERGY                      ONGC: ONGC
35           POWER GRID            POWER           POWER GRID: POWERGRID
36        RELIANCE IND.           ENERGY         RELIANCE IND.: RELIANCE
37                  SBI          BANKING                       SBI: SBIN
38   SBI LIFE INSURANCE        INSURANCE     SBI LIFE INSURANCE: SBILIFE
39      SHRIRAM FINANCE          FINANCE     SHRIRAM FINANCE: SHRIRAMFIN
40           SUN PHARMA  PHARMACEUTICALS           SUN PHARMA: SUNPHARMA
41        TATA CONSUMER             FMCG     TATA CONSUMER: TATACONSUMER
42          TATA MOTORS      AUTOMOBILES         TATA MOTORS: TATAMOTORS
43           TATA STEEL            STEEL           TATA STEEL: TATASTEEL
44                  TCS         SOFTWARE                        TCS: TCS
45        TECH MAHINDRA         SOFTWARE            TECH MAHINDRA: TECHM
46                TITAN        RETAILING                    TITAN: TITAN
47                TRENT        RETAILING                    TRENT: TRENT
48     ULTRATECH CEMENT           CEMENT    ULTRATECH CEMENT: ULTRACEMCO
49                WIPRO         SOFTWARE                    WIPRO: WIPRO

In [97]:
df1=pd.read_csv("D:\Data_Driven_stock_project\comb_stock.csv")

In [98]:
df1

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01 05:30:00,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01 05:30:00,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01 05:30:00,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01 05:30:00,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01 05:30:00,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22 05:30:00,657.30,647.40,2024-11,652.95,3586402
13196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.40,4742.00,2024-11,4778.40,394712
13197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.90,1127.55,2024-11,1136.65,16687505
13198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.30,1729.55,2024-11,1743.55,12386806
13199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.90,9444.10,2024-11,9545.00,619823

In [99]:
df_sorted = df1.sort_values(by='Ticker')

In [100]:
df_sorted

,Ticker,close,date,high,low,month,open,volume
524,ADANIENT,2225.40,2023-11-15 05:30:00,2250.00,2220.50,2023-11,2240.00,696475
9524,ADANIENT,3185.95,2024-08-07 05:30:00,3190.00,3112.00,2024-08,3118.00,1868169
3824,ADANIENT,3228.60,2024-02-20 05:30:00,3269.80,3210.15,2024-02,3267.00,1467630
6324,ADANIENT,2835.95,2024-05-07 05:30:00,2905.35,2822.00,2024-05,2889.95,1262311
11474,ADANIENT,3116.00,2024-10-03 05:30:00,3196.35,3084.10,2024-10,3150.00,1309703
...,...,...,...,...,...,...,...,...
1316,WIPRO,422.60,2023-12-08 05:30:00,424.50,415.00,2023-12,418.80,7739561
3916,WIPRO,531.05,2024-02-22 05:30:00,533.00,521.45,2024-02,522.80,7298241
10516,WIPRO,524.85,2024-09-05 05:30:00,526.00,519.50,2024-09,521.20,6034559
766,WIPRO,400.25,2023-11-22 05:30:00,402.60,399.10,2023-11,402.50,2659291
8766,WIPRO,559.70,2024-07-16 05:30:00,562.60,556.40,2024-07,561.85,5619531

In [113]:
df_c= pd.read_csv("D:\Data_Driven_stock_project\comb_sector.csv")

In [114]:
df_c

,Ticker,close,date,high,low,month,open,volume,sector
0,ADANIENT,2217.30,01-11-2023 05:30,2312.25,2207.00,2023-11,2299.00,1666579,MISCELLANEOUS
1,ADANIENT,2215.30,02-11-2023 05:30,2297.95,2204.20,2023-11,2247.00,2340997,MISCELLANEOUS
2,ADANIENT,2229.85,03-11-2023 05:30,2279.00,2215.00,2023-11,2215.30,1853300,MISCELLANEOUS
3,ADANIENT,2246.00,06-11-2023 05:30,2260.00,2233.00,2023-11,2253.95,770061,MISCELLANEOUS
4,ADANIENT,2233.35,07-11-2023 05:30,2260.00,2226.65,2023-11,2257.00,641554,MISCELLANEOUS
...,...,...,...,...,...,...,...,...,...
13195,WIPRO,566.70,14-11-2024 05:30,574.55,564.20,2024-11,568.95,4891760,SOFTWARE
13196,WIPRO,552.85,18-11-2024 05:30,566.70,540.30,2024-11,566.70,7644882,SOFTWARE
13197,WIPRO,562.00,19-11-2024 05:30,569.80,554.70,2024-11,556.00,6459889,SOFTWARE
13198,WIPRO,557.15,21-11-2024 05:30,567.60,555.30,2024-11,562.00,5836304,SOFTWARE
13199,WIPRO,571.65,22-11-2024 05:30,573.60,557.90,2024-11,561.95,7366616,SOFTWARE

In [115]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   sector  13200 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 928.2+ KB

In [149]:
df1= pd.read_csv("D:\Data_Driven_stock_project\comb_sector.csv",parse_dates=['date'])

In [150]:
df1

,Ticker,close,date,high,low,month,open,volume,sector
0,ADANIENT,2217.30,01-11-2023 05:30,2312.25,2207.00,2023-11,2299.00,1666579,MISCELLANEOUS
1,ADANIENT,2215.30,02-11-2023 05:30,2297.95,2204.20,2023-11,2247.00,2340997,MISCELLANEOUS
2,ADANIENT,2229.85,03-11-2023 05:30,2279.00,2215.00,2023-11,2215.30,1853300,MISCELLANEOUS
3,ADANIENT,2246.00,06-11-2023 05:30,2260.00,2233.00,2023-11,2253.95,770061,MISCELLANEOUS
4,ADANIENT,2233.35,07-11-2023 05:30,2260.00,2226.65,2023-11,2257.00,641554,MISCELLANEOUS
...,...,...,...,...,...,...,...,...,...
13195,WIPRO,566.70,14-11-2024 05:30,574.55,564.20,2024-11,568.95,4891760,SOFTWARE
13196,WIPRO,552.85,18-11-2024 05:30,566.70,540.30,2024-11,566.70,7644882,SOFTWARE
13197,WIPRO,562.00,19-11-2024 05:30,569.80,554.70,2024-11,556.00,6459889,SOFTWARE
13198,WIPRO,557.15,21-11-2024 05:30,567.60,555.30,2024-11,562.00,5836304,SOFTWARE
13199,WIPRO,571.65,22-11-2024 05:30,573.60,557.90,2024-11,561.95,7366616,SOFTWARE

In [151]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   sector  13200 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 928.2+ KB

In [152]:
# Ensure clean columns
df1['Ticker'] = df1['Ticker'].str.strip().str.upper()
df1['sector'] = df1['sector'].str.strip().str.title()

In [153]:
df1

,Ticker,close,date,high,low,month,open,volume,sector
0,ADANIENT,2217.30,01-11-2023 05:30,2312.25,2207.00,2023-11,2299.00,1666579,Miscellaneous
1,ADANIENT,2215.30,02-11-2023 05:30,2297.95,2204.20,2023-11,2247.00,2340997,Miscellaneous
2,ADANIENT,2229.85,03-11-2023 05:30,2279.00,2215.00,2023-11,2215.30,1853300,Miscellaneous
3,ADANIENT,2246.00,06-11-2023 05:30,2260.00,2233.00,2023-11,2253.95,770061,Miscellaneous
4,ADANIENT,2233.35,07-11-2023 05:30,2260.00,2226.65,2023-11,2257.00,641554,Miscellaneous
...,...,...,...,...,...,...,...,...,...
13195,WIPRO,566.70,14-11-2024 05:30,574.55,564.20,2024-11,568.95,4891760,Software
13196,WIPRO,552.85,18-11-2024 05:30,566.70,540.30,2024-11,566.70,7644882,Software
13197,WIPRO,562.00,19-11-2024 05:30,569.80,554.70,2024-11,556.00,6459889,Software
13198,WIPRO,557.15,21-11-2024 05:30,567.60,555.30,2024-11,562.00,5836304,Software
13199,WIPRO,571.65,22-11-2024 05:30,573.60,557.90,2024-11,561.95,7366616,Software

In [154]:
# Sort for group operations
df1 = df1.sort_values(by=['Ticker', 'date'])

# Calculate daily return
df1['daily_return'] = df1.groupby('Ticker')['close'].pct_change()

# Calculate cumulative return (total growth from start to end of year)
df1['avg_yearly_return'] = df1.groupby('Ticker')['daily_return'].transform(lambda x: (1 + x).cumprod() - 1)

In [155]:
# Get the last available cumulative return per stock
yearly_returns = df1.groupby('Ticker').last().reset_index()

In [156]:


# Keep only needed columns
yearly_returns = yearly_returns[['Ticker', 'sector', 'avg_yearly_return']]

In [157]:
# Average yearly return per sector
sector_avg_return = (yearly_returns.groupby('sector')['avg_yearly_return'].mean().reset_index() 
                     .sort_values(by='avg_yearly_return', ascending=False))

sector_avg_return['avg_yearly_return'] = (sector_avg_return['avg_yearly_return'] * 100).round(2)

In [158]:
yearly_returns

        Ticker           sector  avg_yearly_return
0     ADANIENT    Miscellaneous               0.01
1   ADANIPORTS    Miscellaneous               0.31
2   APOLLOHOSP    Miscellaneous               0.22
3   ASIANPAINT           Paints              -0.14
4     AXISBANK          Banking               0.06
5   BAJAJ-AUTO      Automobiles               0.47
6   BAJAJFINSV          Finance               0.04
7   BAJFINANCE          Finance              -0.06
8          BEL          Defence               0.54
9   BHARTIARTL          Telecom               0.59
10        BPCL           Energy               0.37
11   BRITANNIA             Fmcg               0.08
12       CIPLA  Pharmaceuticals               0.24
13   COALINDIA           Mining               0.18
14     DRREDDY  Pharmaceuticals               0.09
15   EICHERMOT      Automobiles               0.21
16      GRASIM         Textiles               0.27
17     HCLTECH         Software               0.19
18    HDFCBANK          Banking               0.02
19    HDFCLIFE        Insurance               0.11
20  HEROMOTOCO      Automobiles               0.21
21    HINDALCO        Aluminium               0.12
22  HINDUNILVR             Fmcg              -0.05
23   ICICIBANK          Banking               0.29
24  INDUSINDBK          Banking              -0.34
25        INFY         Software               0.13
26         ITC   Food & Tobacco               0.04
27    JSWSTEEL            Steel               0.10
28   KOTAKBANK          Banking              -0.09
29          LT      Engineering               0.03
30         M&M      Automobiles               0.60
31      MARUTI      Automobiles               0.08
32   NESTLEIND   Food & Tobacco              -0.17
33        NTPC            Power               0.32
34        ONGC           Energy               0.30
35   POWERGRID            Power               0.35
36    RELIANCE           Energy               0.03
37     SBILIFE        Insurance               0.13
38        SBIN          Banking               0.28
39  SHRIRAMFIN          Finance               0.53
40   SUNPHARMA  Pharmaceuticals               0.47
41  TATACONSUM             Fmcg              -0.06
42  TATAMOTORS      Automobiles               0.05
43   TATASTEEL            Steel               0.06
44         TCS         Software               0.04
45       TECHM         Software               0.24
46       TITAN        Retailing              -0.11
47       TRENT        Retailing               1.37
48  ULTRACEMCO           Cement               0.06
49       WIPRO         Software               0.16

In [159]:
sector_avg_return

             sector  avg_yearly_return
16        Retailing              63.15
19          Telecom              59.18
4           Defence              54.04
15            Power              33.21
20         Textiles              27.23
1       Automobiles              27.09
14  Pharmaceuticals              26.73
5            Energy              23.31
11           Mining              18.40
12    Miscellaneous              18.16
7           Finance              17.34
17         Software              15.22
0         Aluminium              12.39
10        Insurance              12.14
18            Steel               8.02
3            Cement               5.75
2           Banking               3.62
6       Engineering               2.75
8              Fmcg              -1.05
9    Food & Tobacco              -6.45
13           Paints             -13.56

In [171]:
corr_matrix_percent

Ticker,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,BHARTIARTL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
Ticker,,,,,,,,,,,,,,,,,,,,,
ADANIENT,100.00,88.28,12.97,27.98,30.71,20.49,37.08,33.98,51.91,27.24,...,17.60,20.51,33.15,42.71,9.99,13.07,28.00,19.69,36.71,21.72
ADANIPORTS,88.28,100.00,16.43,26.90,37.94,21.05,40.98,40.24,58.09,31.01,...,21.80,21.93,33.88,46.19,12.58,13.69,29.43,20.40,40.59,23.39
APOLLOHOSP,12.97,16.43,100.00,25.02,16.76,21.67,24.08,19.92,21.47,21.89,...,28.60,9.12,20.41,25.57,9.13,14.53,24.39,7.92,26.52,21.71
ASIANPAINT,27.98,26.90,25.02,100.00,13.81,16.07,24.07,28.94,14.60,13.29,...,21.63,24.65,9.85,28.54,14.63,14.47,28.98,23.69,27.22,13.11
AXISBANK,30.71,37.94,16.76,13.81,100.00,18.22,41.96,36.63,32.63,24.05,...,14.81,14.44,23.83,36.31,10.55,12.96,14.32,17.86,40.33,19.59
BAJAJ-AUTO,20.49,21.05,21.67,16.07,18.22,100.00,23.38,17.64,23.23,27.57,...,15.88,19.03,30.02,29.17,2.10,3.72,19.14,22.18,24.07,11.74
BAJAJFINSV,37.08,40.98,24.08,24.07,41.96,23.38,100.00,73.91,35.30,26.25,...,20.54,28.68,28.02,46.83,22.64,18.57,29.10,20.27,47.80,31.52
BAJFINANCE,33.98,40.24,19.92,28.94,36.63,17.64,73.91,100.00,30.84,28.45,...,12.90,22.47,21.03,38.56,16.53,14.81,23.80,23.07,44.46,23.44
BEL,51.91,58.09,21.47,14.60,32.63,23.23,35.30,30.84,100.00,30.13,...,16.57,17.37,36.83,51.80,11.85,21.13,15.43,26.70,44.52,25.37
BHARTIARTL,27.24,31.01,21.89,13.29,24.05,27.57,26.25,28.45,30.13,100.00,...,25.99,25.02,26.29,30.95,17.88,25.41,27.97,26.12,35.62,24.83
BPCL,46.04,50.30,17.42,21.15,23.49,21.45,34.95,26.77,50.92,26.43,...,20.52,15.63,43.86,47.05,18.24,20.07,26.87,21.64,39.60,21.25
BRITANNIA,12.49,13.01,23.44,43.26,13.42,9.50,23.36,21.22,6.91,11.88,...,18.95,41.20,10.03,11.14,11.46,12.88,7.09,3.48,18.90,16.38
CIPLA,9.06,9.00,22.02,14.69,7.82,2.65,14.04,4.94,7.72,10.99,...,41.75,7.34,4.70,13.10,7.67,4.03,9.99,12.71,11.14,8.21
COALINDIA,49.50,54.54,24.54,18.97,32.29,22.76,28.67,28.42,61.98,25.58,...,18.17,20.58,40.67,53.10,9.54,17.23,23.76,26.67,32.92,23.45
DRREDDY,17.16,17.67,23.57,14.84,9.04,10.77,27.09,8.97,13.73,17.87,...,41.06,12.39,20.59,20.47,23.45,21.45,13.44,17.65,26.26,27.37
EICHERMOT,32.22,27.02,28.22,25.36,28.86,27.32,24.71,18.25,27.88,28.48,...,17.17,17.84,31.50,31.76,13.46,18.42,26.78,23.67,31.41,25.52
GRASIM,33.77,35.23,24.81,33.55,36.27,18.57,44.00,36.53,33.41,28.73,...,22.10,28.37,34.15,46.22,18.18,16.13,35.98,23.87,57.83,22.77
HCLTECH,13.29,14.71,27.06,12.08,9.44,12.84,27.80,18.01,21.56,25.92,...,16.40,19.63,25.28,26.99,64.10,55.67,19.82,19.86,21.85,60.40
HDFCBANK,32.51,37.42,10.17,24.74,45.19,18.49,32.44,32.83,32.74,19.47,...,6.70,10.78,21.61,38.75,2.92,19.49,17.97,10.97,36.39,18.09
HDFCLIFE,21.11,23.36,13.21,19.41,25.04,19.05,33.61,29.69,23.84,20.69,...,15.82,20.94,21.37,26.39,11.15,10.07,20.05,20.49,23.89,18.50
HEROMOTOCO,21.19,19.82,24.17,17.35,16.11,39.28,22.90,15.93,8.18,18.58,...,22.78,21.95,29.12,28.20,11.82,10.82,29.68,21.13,26.88,19.85
HINDALCO,30.51,33.22,5.89,21.25,21.99,22.48,29.86,25.66,37.16,29.25,...,24.85,17.54,36.91,62.58,16.22,22.88,24.49,26.88,31.45,25.15
HINDUNILVR,-1.00,0.39,10.99,27.34,1.42,13.38,16.15,13.80,-6.36,15.87,...,6.27,42.61,8.32,8.60,14.90,13.51,19.58,8.07,16.62,17.83
ICICIBANK,39.29,43.94,14.79,15.08,64.92,10.90,42.27,34.07,30.64,35.08,...,19.58,11.97,20.06,34.35,15.87,15.33,13.60,12.14,43.11,21.21
INDUSINDBK,40.06,42.78,11.79,18.38,34.69,19.38,41.99,40.77,31.68,23.41,...,11.02,25.93,32.51,41.03,7.14,10.14,23.53,19.04,33.47,19.77
INFY,9.25,13.84,9.95,9.20,6.22,-1.96,24.18,18.50,14.98,27.40,...,14.86,26.13,18.64,17.78,71.98,64.89,20.50,14.85,22.96,57.35
ITC,24.96,27.31,17.20,29.01,26.29,14.01,30.08,29.91,22.34,26.33,...,18.83,31.14,18.99,24.47,16.79,21.65,31.79,14.79,26.00,22.52
JSWSTEEL,40.14,42.94,26.81,32.43,35.91,22.12,44.28,38.22,45.25,36.12,...,25.33,22.93,41.18,79.13,20.70,25.65,30.39,25.90,55.28,35.23
KOTAKBANK,23.12,29.34,12.79,15.68,30.06,7.98,25.93,30.57,25.85,30.37,...,8.73,18.86,15.57,26.27,9.53,15.19,14.59,8.45,33.30,23.49
LT,48.38,51.73,22.07,20.81,34.84,16.44,40.74,37.80,59.33,31.86,...,16.59,16.52,34.73,48.28,20.55,20.03,21.55,17.48,46.90,31.59
M&M,30.60,31.70,24.14,12.40,23.71,27.46,33.49,25.17,36.62,28.12,...,27.69,17.38,40.56,42.25,17.59,21.17,28.08,26.25,42.86,29.63
MARUTI,31.82,29.51,18.97,25.24,24.89,34.19,31.75,27.44,21.55,34.98,...,19.25,19.38,38.82,38.48,16.31,14.26,32.17,18.38,35.13,20.30
NESTLEIND,9.63,9.03,22.46,26.71,14.56,15.53,28.46,25.00,6.04,9.87,...,16.38,38.46,13.60,12.61,9.97,4.99,24.32,15.43,27.82,17.14
NTPC,55.24,61.46,18.26,22.15,38.14,20.20,39.59,32.41,61.20,36.61,...,23.31,17.95,41.37,53.53,10.68,18.09,32.94,22.84,45.54,19.18
ONGC,48.76,52.80,16.72,12.71,31.91,19.13,31.91,32.11,57.63,34.08,...,22.01,17.47,44.47,49.66,16.78,23.26,19.57,21.40,41.01,29.15
POWERGRID,40.41,51.35,17.72,10.97,29.52,17.20,31.55,24.55,54.34,31.32,...,25.14,14.58,36.02,49.93,10.13,14.71,20.62,20.20,40.48,16.14
RELIANCE,48.57,51.59,22.51,29.15,43.35,25.63,41.58,41.15,49.57,35.39,...,28.44,20.06,39.75,44.62,24.22,25.75,33.01,27.94,49.11,35.28
SBILIFE,28.58,27.87,15.56,20.61,17.99,19.65,41.52,34.17,20.50,23.52,...,14.74,20.78,22.56,22.80,17.03,13.76,20.01,18.14,25.74,24.68
SBIN,55.06,57.91,16.98,9.53,50.84,14.22,42.43,39.43,57.57,28.50,...,10.95,11.17,37.03,48.24,15.89,17.94,20.96,26.85,42.54,23.42
SHRIRAMFIN,42.20,47.46,27.10,21.39,42.91,28.96,48.63,45.98,47.16,35.24,...,20.11,18.22,35.43,45.44,11.91,21.69,25.42,21.64,48.74,30.28
SUNPHARMA,17.60,21.80,28.60,21.63,14.81,15.88,20.54,12.90,16.57,25.99,...,100.00,16.39,29.30,26.40,14.00,15.75,22.41,26.32,23.61,18.86
TATACONSUM,20.51,21.93,9.12,24.65,14.44,19.03,28.68,22.47,17.37,25.02,...,16.39,100.00,17.22,22.58,26.63,20.94,30.51,18.12,24.59,25.39
TATAMOTORS,33.15,33.88,20.41,9.85,23.83,30.02,28.02,21.03,36.83,26.29,...,29.30,17.22,100.00,52.53,24.61,28.35,26.89,22.08,36.22,32.18
TATASTEEL,42.71,46.19,25.57,28.54,36.31,29.17,46.83,38.56,51.80,30.95,...,26.40,22.58,52.53,100.00,24.25,28.07,28.70,22.02,48.15,32.78
TCS,9.99,12.58,9.13,14.63,10.55,2.10,22.64,16.53,11.85,17.88,...,14.00,26.63,24.61,24.25,100.00,57.60,13.20,12.11,24.33,60.16
TECHM,13.07,13.69,14.53,14.47,12.96,3.72,18.57,14.81,21.13,25.41,...,15.75,20.94,28.35,28.07,57.60,100.00,22.92,15.02,26.89,59.85
TITAN,28.00,29.43,24.39,28.98,14.32,19.14,29.10,23.80,15.43,27.97,...,22.41,30.51,26.89,28.70,13.20,22.92,100.00,18.87,35.29,25.54
TRENT,19.69,20.40,7.92,23.69,17.86,22.18,20.27,23.07,26.70,26.12,...,26.32,18.12,22.08,22.02,12.11,15.02,18.87,100.00,29.51,13.88
ULTRACEMCO,36.71,40.59,26.52,27.22,40.33,24.07,47.80,44.46,44.52,35.62,...,23.61,24.59,36.22,48.15,24.33,26.89,35.29,29.51,100.00,29.65
WIPRO,21.72,23.39,21.71,13.11,19.59,11.74,31.52,23.44,25.37,24.83,...,18.86,25.39,32.18,32.78,60.16,59.85,25.54,13.88,29.65,100.00

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st
from sqlalchemy import create_engine
import seaborn as sns

# --- MySQL Connection ---
engine = create_engine('mysql+mysqlconnector://3RpS6E8vJViaNcJ.root:5mAbJNUlK8UUO6DW@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/nifty50_db')

# Load your data
sql_df = pd.read_sql("SELECT * FROM nifty50_tb", con=engine)

df = sql_df.sort_values(['Ticker', 'date'])
# Calculate daily percentage return per stock
df['daily_return'] = df.groupby('Ticker')['close'].pct_change()
# df['daily_return'] = (df['daily_return'] * 100).round(2)  # Convert to %
#Pivot the data: rows = date, columns = stocks, values = daily returns
returns_pivot = df.pivot(index='date', columns='Ticker', values='daily_return')
#Calculate Correlation Matrix using pandas .corr()
corr_matrix = returns_pivot.corr()

In [179]:
corr_matrix = corr_matrix.round(2)

In [180]:
corr_matrix

Ticker,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,BHARTIARTL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
Ticker,,,,,,,,,,,,,,,,,,,,,
ADANIENT,1.00,0.79,0.45,-0.16,0.40,0.52,0.02,-0.25,0.49,0.36,...,0.42,0.71,0.71,0.67,0.50,0.18,0.34,0.30,0.45,0.50
ADANIPORTS,0.79,1.00,0.74,-0.22,0.70,0.85,0.18,-0.28,0.88,0.78,...,0.78,0.75,0.89,0.80,0.78,0.61,0.02,0.73,0.80,0.74
APOLLOHOSP,0.45,0.74,1.00,-0.12,0.49,0.86,0.53,-0.19,0.68,0.84,...,0.94,0.54,0.57,0.39,0.83,0.85,0.09,0.86,0.77,0.88
ASIANPAINT,-0.16,-0.22,-0.12,1.00,0.06,-0.12,0.49,0.64,-0.22,-0.14,...,-0.18,0.07,-0.22,-0.35,0.00,0.00,0.45,-0.05,0.10,-0.21
AXISBANK,0.40,0.70,0.49,0.06,1.00,0.67,0.31,0.10,0.83,0.72,...,0.52,0.39,0.48,0.64,0.50,0.64,-0.20,0.68,0.83,0.59
BAJAJ-AUTO,0.52,0.85,0.86,-0.12,0.67,1.00,0.53,-0.08,0.84,0.95,...,0.93,0.61,0.72,0.68,0.79,0.78,0.03,0.93,0.81,0.77
BAJAJFINSV,0.02,0.18,0.53,0.49,0.31,0.53,1.00,0.54,0.22,0.51,...,0.52,0.15,0.02,0.01,0.40,0.56,0.33,0.58,0.45,0.37
BAJFINANCE,-0.25,-0.28,-0.19,0.64,0.10,-0.08,0.54,1.00,-0.17,-0.09,...,-0.23,-0.20,-0.37,-0.16,-0.27,-0.07,0.29,-0.07,0.02,-0.28
BEL,0.49,0.88,0.68,-0.22,0.83,0.84,0.22,-0.17,1.00,0.89,...,0.76,0.49,0.70,0.77,0.66,0.75,-0.30,0.83,0.87,0.69
BHARTIARTL,0.36,0.78,0.84,-0.14,0.72,0.95,0.51,-0.09,0.89,1.00,...,0.92,0.44,0.58,0.61,0.72,0.89,-0.18,0.97,0.84,0.76
BPCL,0.67,0.91,0.82,-0.23,0.57,0.90,0.31,-0.37,0.80,0.83,...,0.89,0.71,0.86,0.71,0.84,0.66,0.03,0.81,0.73,0.75
BRITANNIA,0.31,0.67,0.71,0.32,0.75,0.79,0.62,0.14,0.76,0.83,...,0.74,0.52,0.48,0.41,0.71,0.82,-0.02,0.84,0.89,0.64
CIPLA,0.55,0.86,0.86,-0.16,0.61,0.94,0.40,-0.22,0.83,0.88,...,0.92,0.67,0.75,0.63,0.83,0.77,0.02,0.88,0.81,0.80
COALINDIA,0.68,0.94,0.72,-0.16,0.66,0.86,0.19,-0.32,0.87,0.80,...,0.79,0.75,0.90,0.78,0.78,0.62,-0.03,0.76,0.77,0.67
DRREDDY,0.47,0.80,0.83,-0.02,0.57,0.80,0.36,-0.29,0.74,0.77,...,0.86,0.69,0.77,0.45,0.89,0.76,0.03,0.80,0.80,0.78
EICHERMOT,0.32,0.75,0.63,-0.13,0.80,0.80,0.33,-0.08,0.92,0.88,...,0.72,0.32,0.57,0.71,0.59,0.74,-0.35,0.84,0.80,0.57
GRASIM,0.38,0.83,0.76,-0.09,0.82,0.88,0.42,-0.10,0.94,0.93,...,0.85,0.50,0.67,0.66,0.76,0.84,-0.22,0.91,0.91,0.75
HCLTECH,0.29,0.52,0.90,-0.03,0.32,0.69,0.57,-0.16,0.47,0.69,...,0.84,0.42,0.35,0.09,0.79,0.84,0.18,0.75,0.66,0.88
HDFCBANK,-0.05,0.27,0.41,0.32,0.64,0.43,0.57,0.40,0.52,0.58,...,0.41,-0.07,-0.03,0.14,0.29,0.68,-0.18,0.61,0.67,0.42
HDFCLIFE,-0.20,0.15,0.52,0.40,0.25,0.39,0.70,0.24,0.29,0.50,...,0.54,0.03,0.02,-0.19,0.48,0.70,0.02,0.61,0.51,0.39
HEROMOTOCO,0.63,0.90,0.74,-0.08,0.79,0.91,0.33,-0.13,0.88,0.86,...,0.78,0.69,0.77,0.76,0.75,0.71,0.01,0.81,0.86,0.73
HINDALCO,0.40,0.74,0.63,-0.03,0.79,0.83,0.44,0.05,0.88,0.89,...,0.72,0.37,0.53,0.72,0.56,0.74,-0.22,0.84,0.81,0.59
HINDUNILVR,-0.05,0.27,0.44,0.62,0.52,0.47,0.65,0.35,0.41,0.52,...,0.45,0.32,0.14,-0.02,0.52,0.66,0.09,0.60,0.67,0.36
ICICIBANK,0.37,0.80,0.82,-0.18,0.78,0.91,0.48,-0.12,0.89,0.96,...,0.90,0.42,0.58,0.60,0.74,0.87,-0.21,0.94,0.86,0.81
INDUSINDBK,0.15,-0.25,-0.54,0.45,-0.24,-0.41,-0.16,0.36,-0.47,-0.60,...,-0.59,0.21,-0.02,-0.08,-0.33,-0.68,0.59,-0.62,-0.38,-0.52
INFY,0.22,0.55,0.85,0.15,0.48,0.70,0.59,-0.10,0.57,0.74,...,0.81,0.48,0.39,0.09,0.85,0.91,0.09,0.81,0.79,0.81
ITC,-0.06,0.33,0.56,0.48,0.46,0.54,0.70,0.31,0.48,0.63,...,0.58,0.25,0.17,-0.00,0.57,0.76,0.04,0.69,0.67,0.41
JSWSTEEL,0.37,0.71,0.75,-0.02,0.77,0.86,0.59,0.08,0.85,0.91,...,0.81,0.30,0.45,0.62,0.62,0.84,-0.16,0.91,0.85,0.71
KOTAKBANK,0.03,0.03,0.19,0.60,0.24,0.12,0.52,0.54,0.06,0.12,...,0.08,0.15,-0.11,-0.15,0.17,0.27,0.36,0.17,0.37,0.18
LT,0.74,0.79,0.59,-0.10,0.54,0.66,0.25,-0.05,0.65,0.57,...,0.58,0.66,0.70,0.63,0.62,0.44,0.33,0.49,0.65,0.61
M&M,0.35,0.78,0.72,-0.18,0.80,0.89,0.38,-0.10,0.95,0.95,...,0.82,0.37,0.57,0.69,0.64,0.83,-0.32,0.92,0.86,0.69
MARUTI,0.52,0.77,0.50,-0.28,0.54,0.77,0.17,-0.18,0.74,0.69,...,0.64,0.54,0.81,0.87,0.52,0.36,-0.11,0.62,0.53,0.40
NESTLEIND,0.39,0.21,-0.03,0.43,0.21,0.14,0.17,0.31,0.00,-0.08,...,-0.04,0.59,0.35,0.24,0.18,-0.19,0.60,-0.08,0.17,0.02
NTPC,0.58,0.90,0.86,-0.10,0.70,0.94,0.47,-0.17,0.89,0.94,...,0.93,0.61,0.73,0.67,0.81,0.82,-0.03,0.92,0.87,0.79
ONGC,0.62,0.91,0.73,-0.21,0.57,0.80,0.14,-0.38,0.81,0.75,...,0.79,0.78,0.93,0.67,0.83,0.60,-0.02,0.71,0.73,0.68
POWERGRID,0.56,0.93,0.77,-0.24,0.77,0.91,0.27,-0.27,0.95,0.91,...,0.86,0.60,0.79,0.77,0.77,0.76,-0.19,0.87,0.86,0.76
RELIANCE,0.80,0.86,0.51,-0.19,0.55,0.64,-0.03,-0.28,0.65,0.48,...,0.52,0.85,0.92,0.75,0.65,0.28,0.21,0.42,0.58,0.57
SBILIFE,0.25,0.62,0.79,0.28,0.53,0.79,0.70,0.05,0.63,0.78,...,0.83,0.56,0.55,0.25,0.84,0.82,0.16,0.84,0.78,0.67
SBIN,0.61,0.91,0.66,-0.43,0.71,0.81,0.08,-0.38,0.91,0.80,...,0.75,0.53,0.80,0.85,0.66,0.59,-0.27,0.73,0.72,0.70
SHRIRAMFIN,0.34,0.75,0.89,0.02,0.69,0.93,0.63,0.01,0.81,0.95,...,0.93,0.50,0.57,0.49,0.79,0.91,-0.03,0.97,0.87,0.79
SUNPHARMA,0.42,0.78,0.94,-0.18,0.52,0.93,0.52,-0.23,0.76,0.92,...,1.00,0.54,0.64,0.49,0.84,0.86,-0.01,0.93,0.77,0.84
TATACONSUM,0.71,0.75,0.54,0.07,0.39,0.61,0.15,-0.20,0.49,0.44,...,0.54,1.00,0.84,0.50,0.75,0.31,0.46,0.41,0.55,0.53
TATAMOTORS,0.71,0.89,0.57,-0.22,0.48,0.72,0.02,-0.37,0.70,0.58,...,0.64,0.84,1.00,0.75,0.74,0.38,0.14,0.53,0.59,0.55
TATASTEEL,0.67,0.80,0.39,-0.35,0.64,0.68,0.01,-0.16,0.77,0.61,...,0.49,0.50,0.75,1.00,0.38,0.28,-0.12,0.50,0.54,0.41
TCS,0.50,0.78,0.83,0.00,0.50,0.79,0.40,-0.27,0.66,0.72,...,0.84,0.75,0.74,0.38,1.00,0.76,0.19,0.76,0.77,0.83
TECHM,0.18,0.61,0.85,0.00,0.64,0.78,0.56,-0.07,0.75,0.89,...,0.86,0.31,0.38,0.28,0.76,1.00,-0.16,0.92,0.85,0.82
TITAN,0.34,0.02,0.09,0.45,-0.20,0.03,0.33,0.29,-0.30,-0.18,...,-0.01,0.46,0.14,-0.12,0.19,-0.16,1.00,-0.16,-0.04,0.03
TRENT,0.30,0.73,0.86,-0.05,0.68,0.93,0.58,-0.07,0.83,0.97,...,0.93,0.41,0.53,0.50,0.76,0.92,-0.16,1.00,0.84,0.78
ULTRACEMCO,0.45,0.80,0.77,0.10,0.83,0.81,0.45,0.02,0.87,0.84,...,0.77,0.55,0.59,0.54,0.77,0.85,-0.04,0.84,1.00,0.79
WIPRO,0.50,0.74,0.88,-0.21,0.59,0.77,0.37,-0.28,0.69,0.76,...,0.84,0.53,0.55,0.41,0.83,0.82,0.03,0.78,0.79,1.00