In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\Data_Driven_stock_project\comb_stock.csv")

In [3]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01 05:30:00,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01 05:30:00,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01 05:30:00,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01 05:30:00,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01 05:30:00,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22 05:30:00,657.30,647.40,2024-11,652.95,3586402
13196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.40,4742.00,2024-11,4778.40,394712
13197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.90,1127.55,2024-11,1136.65,16687505
13198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.30,1729.55,2024-11,1743.55,12386806
13199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.90,9444.10,2024-11,9545.00,619823

In [4]:
df.isnull().sum()

Ticker    0
close     0
date      0
high      0
low       0
month     0
open      0
volume    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
dtypes: float64(4), int64(1), object(3)
memory usage: 825.1+ KB

In [ ]:
from dateutil import parser

# Apply dateutil.parser to handle both formats automatically
df['date'] =df['date'].apply(lambda x: parser.parse(x).date() if pd.notnull(x) else None)

In [8]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475
...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
dtypes: float64(4), int64(1), object(3)
memory usage: 825.1+ KB

In [11]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  datetime64[ns]
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 825.1+ KB

In [13]:
df['year']=df['date'].dt.year

In [14]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [19]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [20]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [23]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   year    13200 non-null  int32
dtypes: float64(4), int32(1), int64(1), object(3)
memory usage: 876.7+ KB

In [25]:
print(df['date'].dtype)

object

In [28]:
df['date'] = pd.to_datetime(df['date'])

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  datetime64[ns]
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   year    13200 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(1), object(2)
memory usage: 876.7+ KB

In [35]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [37]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [38]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   year    13200 non-null  int32
dtypes: float64(4), int32(1), int64(1), object(3)
memory usage: 876.7+ KB

In [40]:
print(df['date'].dtype)

object

In [41]:
df['date'] = pd.to_datetime(df['date'])

In [42]:
print(df['date'].dtype)

datetime64[ns]

In [43]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [44]:
df['date'] = df['date'].dt.date

In [45]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  object
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  object
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   year    13200 non-null  int32
dtypes: float64(4), int32(1), int64(1), object(3)
memory usage: 876.7+ KB

In [47]:
print(df['date'].head())

0    2023-11-01
1    2023-11-01
2    2023-11-01
3    2023-11-01
4    2023-11-01
Name: date, dtype: object

In [62]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  13200 non-null  object
 1   close   13200 non-null  float64
 2   date    13200 non-null  datetime64[ns]
 3   high    13200 non-null  float64
 4   low     13200 non-null  float64
 5   month   13200 non-null  int64
 6   open    13200 non-null  float64
 7   volume  13200 non-null  int64
 8   year    13200 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(2), object(1)
memory usage: 876.7+ KB

In [64]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [59]:
print(type(df['date'].iloc[0]))
print(df['date'].iloc[0])

<class 'datetime.date'>
2023-11-01

In [52]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [60]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [58]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [65]:
df

,Ticker,close,date,high,low,month,open,volume,year
0,SBIN,566.40,2023-11-01,569.65,563.85,2023-11,566.25,13575575,2023
1,BAJFINANCE,7471.90,2023-11-01,7549.00,7457.65,2023-11,7520.00,462778,2023
2,TITAN,3173.40,2023-11-01,3212.90,3168.35,2023-11,3193.85,756820,2023
3,ITC,428.10,2023-11-01,431.10,425.50,2023-11,430.00,7990245,2023
4,TCS,3330.65,2023-11-01,3371.60,3311.00,2023-11,3355.00,1563475,2023
...,...,...,...,...,...,...,...,...,...
13195,HINDALCO,652.10,2024-11-22,657.30,647.40,2024-11,652.95,3586402,2024
13196,HEROMOTOCO,4794.10,2024-11-22,4808.40,4742.00,2024-11,4778.40,394712,2024
13197,AXISBANK,1142.40,2024-11-22,1147.90,1127.55,2024-11,1136.65,16687505,2024
13198,HDFCBANK,1745.60,2024-11-22,1754.30,1729.55,2024-11,1743.55,12386806,2024
13199,BAJAJ-AUTO,9481.65,2024-11-22,9602.90,9444.10,2024-11,9545.00,619823,2024

In [67]:
#save the Ticker data in separate csv files under one folder

import os

# Create a folder to store output files
output_folder = 'nifty50'
os.makedirs(output_folder, exist_ok=True)

# Loop through each unique ticker
for ticker in df['Ticker'].unique(): # here picks each unique ticker name is SBIN', 'BAJFINANCE', 'TITAN', 'ITC ...
    ticker_df = df[df['Ticker'] == ticker]  # filter dat
    file_name = f"{ticker}.csv"             # create filename like SBIN.csv...so on...
    file_path = os.path.join(output_folder, file_name)  # full path
    ticker_df.to_csv(file_path, index=False)  # save CSV
    print(f"Saved: {file_name}")

Saved: SBIN.csv
Saved: BAJFINANCE.csv
Saved: TITAN.csv
Saved: ITC.csv
Saved: TCS.csv
Saved: LT.csv
Saved: TATACONSUM.csv
Saved: RELIANCE.csv
Saved: HCLTECH.csv
Saved: JSWSTEEL.csv
Saved: ULTRACEMCO.csv
Saved: POWERGRID.csv
Saved: INFY.csv
Saved: TRENT.csv
Saved: BHARTIARTL.csv
Saved: TATAMOTORS.csv
Saved: WIPRO.csv
Saved: TECHM.csv
Saved: NTPC.csv
Saved: HINDUNILVR.csv
Saved: APOLLOHOSP.csv
Saved: M&M.csv
Saved: GRASIM.csv
Saved: ICICIBANK.csv
Saved: ADANIENT.csv
Saved: ADANIPORTS.csv
Saved: BEL.csv
Saved: BAJAJFINSV.csv
Saved: EICHERMOT.csv
Saved: COALINDIA.csv
Saved: MARUTI.csv
Saved: INDUSINDBK.csv
Saved: ASIANPAINT.csv
Saved: TATASTEEL.csv
Saved: HDFCLIFE.csv
Saved: DRREDDY.csv
Saved: SUNPHARMA.csv
Saved: KOTAKBANK.csv
Saved: SHRIRAMFIN.csv
Saved: NESTLEIND.csv
Saved: ONGC.csv
Saved: CIPLA.csv
Saved: BPCL.csv
Saved: BRITANNIA.csv
Saved: SBILIFE.csv
Saved: HINDALCO.csv
Saved: HEROMOTOCO.csv
Saved: AXISBANK.csv
Saved: HDFCBANK.csv
Saved: BAJAJ-AUTO.csv

In [144]:
ticker_map = {ticker: i for i, ticker in enumerate(df['Ticker'].unique(), start=1)}
df['stock_no'] = df['Ticker'].map(ticker_map)

# Reorder columns to make 'stock_no' the first column
cols = ['stock_no'] + [col for col in df.columns if col != 'stock_no']
df = df[cols]

In [133]:
df['month'] = df['date'].dt.month

In [134]:
df['month'] = df['month'].astype(int)

In [68]:
df.to_csv("nifty50_cleaned.csv", index=False)

In [3]:
import mysql.connector
sql_stock=mysql.connector.connect(host="gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
                             user="3RpS6E8vJViaNcJ.root",password="5mAbJNUlK8UUO6DW",port=4000)

In [4]:
cursor = sql_stock.cursor()

In [5]:
cursor.execute("show databases")
for i in cursor:
  print(i)

('INFORMATION_SCHEMA',)
('PERFORMANCE_SCHEMA',)
('gravity_books',)
('imdb_2024',)
('movies_2024',)
('mysql',)
('nifty50_db',)
('panimalar',)
('sqltst',)
('test',)

In [ ]:
cursor.execute("CREATE DATABASE nifty50_db")

In [7]:
cursor.execute("show databases")
for i in cursor:
  print(i)

('INFORMATION_SCHEMA',)
('PERFORMANCE_SCHEMA',)
('gravity_books',)
('imdb_2024',)
('movies_2024',)
('mysql',)
('nifty50_db',)
('panimalar',)
('sqltst',)
('test',)

In [8]:
sql_stock=mysql.connector.connect(host="gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
                             user="3RpS6E8vJViaNcJ.root",password="5mAbJNUlK8UUO6DW",port=4000,database="nifty50_db",connection_timeout=60)

In [9]:
cursor = sql_stock.cursor()

In [10]:
cursor.execute("SELECT DATABASE()")
print(f"Connected to: {cursor.fetchone()[0]}")

Connected to: nifty50_db

In [11]:
cursor.execute("USE nifty50_db;")

In [193]:
try:
    create_table_query = """
    CREATE TABLE nifty50_tb (
    stock_no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Ticker VARCHAR(10),
    close DECIMAL(15, 2),
    date DATE,
    high DECIMAL(15, 2),
    low DECIMAL(15, 2),
    month INT,
    open DECIMAL(15, 2),
    volume BIGINT,
    year INT
);
    """
    cursor.execute(create_table_query)
    print("✅ Table 'nifty50_tb' created or already exists.")
except Exception as e:
    print(f"❌ Error: {e}")

✅ Table 'nifty50_tb' created or already exists.

In [205]:
sql_stock.commit()

In [12]:
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()
print("Tables in the database:", tables)

Tables in the database: [('nifty50_tb',)]

In [242]:
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()
print("Tables in the database:", tables)

# Extract table names as strings
table_names = [t[0] for t in tables]

# Check if 'nifty50_tb' exists
if 'nifty50_tb' in table_names:
    print("✅ Table 'nifty50_tb' created or already exists.")
else:
    print("❌ Table 'nifty50_tb' was not created.")

Tables in the database: [('nifty50_tb',)]
✅ Table 'nifty50_tb' created or already exists.

In [198]:
if 'stock_no' in df.columns:
    df.drop(columns='stock_no', inplace=True)

C:\Users\gthir\AppData\Local\Temp\ipykernel_22484\263160727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='stock_no', inplace=True)

In [199]:
from sqlalchemy import create_engine

# Set up the connection to MySQL using SQLAlchemy
engine = create_engine('mysql+mysqlconnector://3RpS6E8vJViaNcJ.root:5mAbJNUlK8UUO6DW@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/nifty50_db')

# Insert the DataFrame into the 'nifty50_tb' table
df.to_sql(name='nifty50_tb', con=engine, index=False, if_exists='append')

print("✅ Data inserted successfully into 'nifty50_tb'.")

✅ Data inserted successfully into 'nifty50_tb'.

In [ ]:
cursor.execute("SELECT * FROM nifty50_tb LIMIT 5;")
result = cursor.fetchall()

# Print the first few rows of the table
for row in result:
    print(row)
print(f"Number of rows in table: {row}")

Number of rows in table: 13200

In [16]:
cursor.execute("SELECT * FROM nifty50_tb LIMIT 5;")